version: '3'

services:
  keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:latest
    command: start --auto-build --db=postgres --features=token-exchange --db-url=jdbc:postgresql://keycloak-db:5432/keycloak --db-username=keycloak --db-password=keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: sso.app.danielr1996.de
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
    labels:
      traefik.enable: true
      traefik.http.routers.keycloak.rule: Host(`sso.app.danielr1996.de`)
      traefik.http.routers.keycloak.tls.certresolver: letsencrypt
      de.danielr1996.bashdoard.name: Keycloak
      de.danielr1996.bashdoard.url: https://sso.app.danielr1996.de
      de.danielr1996.bashdoard.icon: /resources/uv5nk/welcome/keycloak/img/favicon.ico
      de.danielr1996.bashdoard.id: keycloak
  keycloak-db:
    restart: unless-stopped
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.5,nolock,soft,rw"
      device: ":/mnt/user/compose-data/keycloak/db"
